Backend Endpoint Interceptors and Updater
ucsb-cs156-f23/proj-organic-f23-6pm-2 pull request #17
Opened 2023-11-25 04:39 UTC by whuang602

- added interceptors to ensure admin and instructor roles are updated properly
- added code to add role_instructor

2023-11-27 17:37 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/organic/Interceptors/RoleUserInterceptor.java
> +                // Collection<? extends GrantedAuthority> currentAuthorities = authentication.getAuthorities();
What do we do with commented out code? 😄 

https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2023-11-27 17:38 UTC, pconrad requested changes
Please see https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2023-11-27 21:04 UTC, ZhenyuYu1 approved these changes
LGTM!

2023-11-27 21:18 UTC, ZhenyuYu1 approved these changes
LGTM!

2023-11-28 01:25 UTC, pconrad approved these changes
LGTM

2023-11-28 21:21 UTC, pconrad requested changes
Ok, the code looks good at first glance.  But I tested this on dokku and it didn't work.

Here's what's supposed to happen:

(1) Login to two different windows in two different browser with two accounts, an admin account and a non-admin account.

(2) In the window for the admin account, toggle the non-admin account to admin using swagger.

(3) In the other window, look at whether the status changes.

What I expect is that in the window of the non-admin user:
(a) They show admin true now (this part works!)
(b) They have ROLE_ADMIN in their roles list (this part does NOT work)
(c) They can now perform admin functions (this part does NOT work).

<img width="409" alt="image" src="https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-2/assets/1119017/62364854-46b1-4356-9953-82a3ccbade92">

After logging out and logging back in, it does work, but that's not what the interceptor is supposed to do. It's supposed to make the change immediately on the next load of a page (even if the user doesn't log out and back in again.)

So, please do some debugging.  You may want to see if there is something from the original proj-gauchoride code that you are missing.

2023-11-28 23:31 UTC, ZhenyuYu1 approved these changes
LGTM!

2023-11-29 18:23 UTC, pconrad approved these changes

2023-11-29 18:23 UTC, merged