Web metadata change
ucsb-cs156-f23/proj-organic-f23-6pm-2 pull request #49
Opened 2023-11-29 05:48 UTC by whuang602

- changed the website's metadata from default "web site created with create-react-app" to UCSB CS156 Project Organic
- also changed website's title

2023-11-29 06:52 UTC, justinchung712 approved these changes
lgtm

2023-11-29 18:39 UTC, pconrad requested changes
Some feedback to consider...

2023-11-29 20:10 UTC, whuang602 commented on frontend/public/index.html
> +    <title>CS156 Project Organic</title>
Understood, changed it back!

2023-11-30 02:38 UTC, pconrad approved these changes
LGTM

2023-11-30 02:55 UTC, SparklyJeff approved these changes
LGTM

2023-11-30 02:55 UTC, vedantshah99 approved these changes
lgtm

2023-11-30 03:33 UTC, merged